FROM python:3.12.6

WORKDIR /package

RUN pip install --no-cache-dir poetry

ENV POETRY_VIRTUALENVS_CREATE=false
RUN poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root

COPY . .
